= Asciidoctor {extension} Extension
:extension: tabset-block
:extension-version: 0.0.3
:latest-antora: 3.0.0-alpha.1
:source-repository: https://gitlab.com/djencks/asciidoctor-{extension}
:description: This asciidoctor block extension renders a description list as a tabset.

== Description

{description}
The original code is by Dan Allen for Couchbase, from https://github.com/couchbase/docs-site/blob/master/lib/tabs-block.js[].

Instead of the direct html output of the original, this extension generates open blocks.
In addition, this extension supports nested tabsets.
Most of the nested tabset support is in the related UI extension.

Nested open blocks are needed for nested tabsets.
Therefore, for convenience, the openblock extension from https://gitlab.com/djencks/asciidoctor-openblock[] is included in this extension.

The code is located at link:{source-repository}[]

This requires the related UI extension, set up for use with my ui-builder project.
Since the ui-builder project is not released to npmjs, this project and the ui extension are not either.

== Installation for Asciidoctor.js

To use in your Asciidoctor documentation project, the simplest way is to have a package.json like this:

[source,json,subs="+attributes"]
----
{
  "description": "---",
  "devDependencies": {
    "@djencks/{extension}": "https://experimental-repo.s3-us-west-1.amazonaws.com/djencks-{extension}-v{extension-version}.tgz"
    "@asciidoctor/core": "^2.2.0",
    "@asciidoctor/cli": "^2.2.0"
  }
}
----

Other than the code in the tests, I don't know how to use this in standalone asciidoctor.js.

== Installation for Antora

To use in your Antora documentation project, the simplest way is to have a package.json like this:

[source,json,subs="+attributes"]
----
{
  "description": "---",
  "scripts": {
    "clean-build": "npm run clean-install;npm run build",
    "clean-install": "rm -rf node_modules/ .cache/ package-lock.json ;npm i --cache=.cache/npm",
    "build": "node_modules/.bin/antora antora-playbook.yml --stacktrace --fetch"
  },
  "devDependencies": {
    "@antora/cli": "^{latest-antora}",
    "@antora/site-generator-default": "^{latest-antora}",
    "@djencks/{extension}": "https://experimental-repo.s3-us-west-1.amazonaws.com/djencks-{extension}-v{extension-version}.tgz",
    "@djencks/{extension}-ui": "https://experimental-repo.s3-us-west-1.amazonaws.com/djencks-{extension}-ui-v{extension-version}.tgz"
  }
}
----

(This will set up an isolated Antora installation and environment)

and to include this in your `antora-playbook.yml` playbook:

[source,yml,subs="+attributes"]
----
asciidoc:
  extensions:
    - "@djencks/asciidoctor-{extension}"
----

== Usage

This renders a description list inside an example block marked `[tabset]` as a tabset.

[source,adoc]
----
[tabset]
====

Tab A::
+
--
[discrete]
== A section

With an explanation!
--

Tab B::
+
--
[discrete]
== A section

With no explanation?
--

Tab C::
+
--
* A multilevel list
** level 2
*** level 3
** level 2
* level 1
--

Tab D::
+
--
A multilevel description list::
It's all about descriptions!
2nd Level:::
With lots of details!
3rd Level::::
And nit-picky micro-details!
--
====
----

Note the use of the `+` continuation to mark the open block as the description of the 'term'.
Note also that sections must be marked `[discrete]` as they are not part of the normal document flow.


== Sample code

There is a simple example demonstrating nested tabsets and links to tabs from the same page and a different page, including links to nested tabs, at https://gitlab.com/djencks/simple-examples[] under extensions/tabset-block-extension.
